### ISSUE TITLE
Tracking issue for alpha release

### ISSUE THREAD

**Issue by tiptenbrink** [DSAV-Dodeka/backend#37]
Issues
* [x] DSAV-Dodeka/dodeka#27 We need to access logs easily
* [x] DSAV-Dodeka/backend#26 logout popup/alert
* [x] DSAV-Dodeka/backend#17 automatic script to create initial values
* [x] DSAV-Dodeka/backend#5 finalize for deployment
